name: first workflow
on: push
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo "welcome to first workflow"
      - name: welcome
        run: echo "welcome to github action"
    

