name: secrets and variables
on: workflow_dispatch
jobs:
  secrets:
    env:
      USERNAME: Admin
      PASSWORD: Admin123
    runs-on: ubuntu-latest
    steps:
      - name: login database
        run: echo "login database using password ${{ secrets.DB_PASSWORD }} and username ${{ vars.DB_USERNAME }}"
      - name: dispaly database credentials
        run: echo "db password is  ${{ secrets.DB_PASSWORD }} and username ${{ vars.DB_USERNAME }}"  
